version: '2'
services:
    eva:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: eva
        ports:
        - "8080:8080"
        - "8800:3000/udp"
        volumes:
        - .:/eva
        depends_on:
        - "mongo"
        - "tts"
    mongo:
        image: mongo
        hostname: mongo
        ports:
        - "27017:27017"
    tts:
        image: parente/espeakbox
        ports:
        - "8081:8080"
